CREATE DATABASE cars;
CREATE DATABASE booking;
CREATE DATABASE identity;

GRANT ALL PRIVILEGES ON DATABASE identity TO postgres;
GRANT ALL PRIVILEGES ON DATABASE booking TO postgres;
GRANT ALL PRIVILEGES ON DATABASE cars TO postgres;
